### ISSUE TITLE
'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Opensitoo** [punk-security/dnsReaper#80]
Al ejecutar la herramienta me da este error y no encuentro la manera de repararlo

Testing with 55 signatures
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\dns\win32util.py", line 48, in run
    self.info.domain = _config_domain(interface.DNSDomain)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\dns\win32util.py", line 26, in _config_domain
    if domain.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by SimonGurney** [comment]
Hmmm, I've not seen this issue before.  

Could you provide some more detail?  How are you running the tool, with a file?

**Comment by vmesel** [comment]
Probably he is not setting the domain, @SimonGurney

**Comment by SimonGurney** [comment]
This was my thought but the --domain arg is mandatory when using the single provider.  Maybe the approach we use to enforce that doesn't work on py3.9?

Do you see the same behaviour?

**Comment by Opensitoo** [comment]
> Hmmm, I've not seen this issue before.
> 
> Could you provide some more detail? How are you running the tool, with a file?

im execute this with >python main.py single --domain stardock.com

https://imgur.com/a/nRvJWlx (this is a cap of the terminal)

**Comment by SimonGurney** [comment]
Wow, that's really broken!  Thanks for sharing.

We dev this with python 3.10 so must have used something too new.  We'll get this fixed.  We have an issue being worked to add testing around the providers which will allow us to test all python versions.

For now, put the domain in a file and use the file provider instead.

**Comment by Opensitoo** [comment]
okey thanks whatever i try to change the python to 3.10

**Comment by SimonGurney** [comment]
@imnotbrandon maybe I broke this when I fixed the early domain lookup bug, can you take a look?

**Comment by Opensitoo** [comment]
I downloaded python 3.10 and tried the file but it still gives me an error

this is a diferente error

https://imgur.com/a/0SU2JsQ

**Comment by imnotbrandon** [comment]
Hey there,
I can't seem to reproduce this issue in a clean environment.

The python 3.9 issue looks like it's having trouble figuring out your machine's DNS servers.

I'm not sure about the python 3.10 issue.

This is what I did:
```shell
git clone git@github.com:punk-security/dnsReaper.git
pip install virtualenv
python -m venv venv
.\venv\Scripts\activate.bat
python main.py single --domain stardock.com
```
![image](https://user-images.githubusercontent.com/971790/183655862-08a3af2c-13b7-475f-914b-689545aa0a81.png)


I can only really conclude that there's an issue with your machine. Perhaps try the docker image?

**Comment by Engr-Asad-Hussain** [comment]
Absolutely! working perfectly I have also tested on local machine using `python main.py`. It takes 44 seconds to complete without any errors.

**Comment by Opensitoo** [comment]
I don't know, it still doesn't leave me well thanks for the help anyway
